version: '2'
services:
  testrpc:
    image: dougvk/mydapp_testrpc:latest
    command: bash -c "testrpc -h 0.0.0.0"
  truffle:
    image: dougvk/mydapp_truffle:latest
    #command: bash -c "truffle migrate && truffle serve"
    command: bash -c "tail -f /dev/null"
    ports:
      - "7001:8080"
    volumes_from:
      - truffle_vol
  truffle_vol:
    image: busybox
    container_name: truffle_vol
    volumes:
      - ../:/app

volumes:
  truffle_vol:
